fixtures:
  repositories:
    inifile: 'git://github.com/simp/puppetlabs-inifile.git'
    stdlib: 'git://github.com/simp/puppetlabs-stdlib.git'
    postgresql: '-b simp-master git://github.com/simp/puppetlabs-postgresql.git'
    firewall: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    concat: 'git://github.com/simp/pupmod-simp-concat.git'
  symlinks:
    puppetdb: '#{source_dir}'
